apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: research-couchdb
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubrenetes.io/component: config
data:  
  leader.ini: |
    [couchdb]
    single_node = true

    [log]
    level = warn

    [admins]
    admin = -pbkdf2-8f501b156b6f2a91661bda68cb682b72ca4e5a8d,53e44a4d733a4077869279cca017db02,10
    follower = -pbkdf2-2ce932a1eb570d7d524f54c4819a351222ec3b3a,8e3299d5e26ee58755346922ccc2b6a1,10    

    [httpd]
    server_options = [{backlog, 1024}, {acceptor_pool_size, 1024}]
    socket_options = [{nodelay, true}]

  follower.ini: |
    [couchdb]
    single_node = true

    [log]
    level = warn
    [admins]
    follower = -pbkdf2-2ce932a1eb570d7d524f54c4819a351222ec3b3a,8e3299d5e26ee58755346922ccc2b6a1,10
    [httpd]
    server_options = [{backlog, 1024}, {acceptor_pool_size, 1024}]
    socket_options = [{nodelay, true}]