apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-web
  labels:
    app.kubernetes.io/name: research-couchdb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubrenetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: research-couchdb
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubrenetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: research-couchdb
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubrenetes.io/component: web
    spec:      
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
        app.kubernetes.io/name: research-couchdb
spec:
  ports:
    - port: 80
  selector:    
    app.kubernetes.io/name: research-couchdb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubrenetes.io/component: web  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-web
  labels:
    app.kubernetes.io/name: research-couchdb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubrenetes.io/component: web
  annotations:    
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
    - host: couchdb-web.k8slocal
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-web
              port:
                number: 80